model_config = {
    "pad": -999999.0,
    "max_steps": 128,
    "components": 5,
    "input_dims": 5,
    "output_dims": 3,
    "min_delay_ms": 2.0,
    "epochs": 200,
    "batch_size": 256,
    "lstm_units": 128,
    "lstm_units_lite": 64,
    "learning_rate": 0.0005,
    "validation_split": 0.1,
    "early_stopping_patience": 20,
    "weights": "model.h5",
    "weights_lite": "model_lite.h5",
    "onnx_model": "touch.onnx",
    "data": "touch_data.jsonl",
}
